services:
  willys-backend:
    build:
      dockerfile: ${DOCKERFILE:-Dockerfile}
    container_name: willys-backend
    ports:
      - '8080:8080'
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.willys-backend.rule=Host(`api.dev-tbm.xyz`)'
      - 'traefik.http.routers.willys-backend.entrypoints=websecure'
      - 'traefik.http.routers.willys-backend.tls.certresolver=myresolver'
      - 'traefik.http.services.willys-backend.loadbalancer.server.port=8080'
      - 'traefik.http.middlewares.request-size-limit.buffering.maxRequestBodyBytes=104857600'
      - 'traefik.http.routers.willys-backend.middlewares=request-size-limit'
    volumes:
      - .:/app
      - /app/node_modules
    command: ['yarn', 'start:prod']
    restart: always
    mem_limit: 2g
    mem_reservation: 1g
  traefik:
    image: traefik:latest
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=youssefbashafcis@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --providers.docker.network=willys_default
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/letsencrypt:/letsencrypt
