export enum NotificationType {
  ORDER_NEW = "ORDER_NEW",
  ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED",
  USER_REGISTERED = "USER_REGISTERED",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_REFUNDED = "PAYMENT_REFUNDED",
}
