export enum PaymentEventType {
  CREATED = "CREATED",
  PROCESSING = "PROCESSING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED",
  STATUS_CHANGED = "STATUS_CHANGED",
  REFUND_REQUESTED = "REFUND_REQUESTED",
  REFUNDED = "REFUNDED",
}
