export enum PermissionModule {
  USERS = 'USERS',
  CATEGORIES = 'CATEGORIES',
  ITEMS = 'ITEMS',
  BUNDLES = 'BUNDLES',
  INGREDIENTS = 'INGREDIENTS',
  BRANCHES = 'BRANCHES',
  ZONES = 'ZONES',
  BRANCH_MENU = 'BRANCH_MENU',
  DISCOUNTS = 'DISCOUNTS',
  PAYMENTS = 'PAYMENTS',
  REFUNDS = 'REFUNDS',
  ROLES = 'ROLES',
}
